### ISSUE TITLE
CPU usage at download

### ISSUE THREAD

**Issue by rvencu** [Wikidepia/crawlingathome-worker#5]
I noticed the download part is single threaded, even if it is async, it only uses 1 CPU.

I would be curious to test a multithreaded download made in this way:
1. count CPU cores
2. split the shard in even parts equal with the number of cores
3. spin out same number of threads and launch parse_wat with different piece of shard in parallel
4. wait for all threads to finish and join back to the main thread

This way we could use more CPU if we have multiple cores. I am curious to see if by using 2 cores in droplet we can gain more speed than the price difference between the 1 core and 2 core droplet. The price difference is: 2.96 for 1 core, 4.15 for 2 cores, i.e. we are looking to speed up the download more than 40%

If you can create a branch with this I will fork it and test various combinations

**Comment by Wikidepia** [comment]
You can try dev branch and change workers here https://github.com/Wikidepia/crawlingathome-worker/blob/dev/crawlingathome.py#L169 to your cpu cores

**Comment by rvencu** [comment]
OK. I can see 16 download threads on my 16 CPU box. Perhaps because of the network bottleneck overall CPU usage was less than 5%. I need to rent a multicpu box at hetzner to try it out again

The main issue is this also needs fine tuning because I only got 3140 images as a result... Process was capped by my DNS provider I guess, it took 2300 seconds

Will be back with more test results

**Comment by Wikidepia** [comment]
Here is my result: 8 core on hetzner 16k images in 15ish minutes

**Comment by rvencu** [comment]
ok, please try on cpx11 with 2 cores. because the 8 core is too expensive

if we can get there less than 1700 seconds for ~15K images then we have a new winner

**Comment by rvencu** [comment]
no joy on low cpu, load is 100% on cpu and download time is much worse than async method
maybe a combination of threading and async would be best for low cpu count (except 1 cpu where the async alone is perfect)

**Comment by rvencu** [comment]
got one error in one worker

tractor._exceptions.RemoteActorError: ('worker_1', '5a60a733-641d-40c4-96e9-4b60d42bf5d8')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tractor/_actor.py", line 477, in _process_messages
    async for msg in chan:
  File "/usr/local/lib/python3.8/dist-packages/tractor/_ipc.py", line 209, in _aiter_recv
    async for item in self.msgstream:
  File "/usr/local/lib/python3.8/dist-packages/tractor/_ipc.py", line 62, in _iter_packets
    for packet in unpacker:
  File "msgpack/_unpacker.pyx", line 518, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 443, in msgpack._cmsgpack.Unpacker._unpack
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 18: invalid start byte

**Comment by rvencu** [comment]
3 cpu - 126k links - 17k images - 60 minutes - reduced to 3 workers
2 cpu - 103k links - 17K images - 66 minutes - reduced to 2 workers
