### ISSUE TITLE
Suggestion to avoid abuse reports

### ISSUE THREAD

**Issue by rvencu** [Wikidepia/crawlingathome-worker#9]
Hi, after some incidents with our scraper, I got a suggestion to spread out requests made to the same domain name.

For this, we need a function that will shuffle parsed_data in such a way that the links to the same domain name are as spread out as possible.

Can you work at that?

**Comment by Wikidepia** [comment]
Is there any reason why? I can just add shuffle but there i cant guarantee will be spread out

**Comment by Wikidepia** [comment]
Oops, I'm sorry I didnt read issue title 😅. I can add shuffle later

**Comment by rvencu** [comment]
Yes, shuffle should be fine since the event is already very rare

going to more complicated stuff (i.e. find more pairs and making random swaps) or creating a score function and apply sophisticated algorithms to ensure score minimization would actually increase computing too much on that single cpu and the benefit will be barely seen
